channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=22.2.2
- pip:
  - mlflow<3,>=2.2
  - cloudpickle==2.0.0
  - lz4==3.1.3
  - numpy==1.21.5
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.0.2
  - scipy==1.9.1
name: mlflow-env
